### ISSUE TITLE
Cannot use JWT secret from file

### ISSUE THREAD

**Issue by jappyjan** [FabInfra/Attraccess#146]
fehler:
```
[Nest] 1  - 06/17/2025, 9:34:20 AM     LOG [InstanceLoader] ScheduleModule dependencies initialized +0ms
[Nest] 1  - 06/17/2025, 9:34:20 AM     LOG [InstanceLoader] ScheduleModule dependencies initialized +0ms
[Nest] 1  - 06/17/2025, 9:34:20 AM     LOG [InstanceLoader] EventEmitterModule dependencies initialized +0ms
[Nest] 1  - 06/17/2025, 9:34:20 AM     LOG [InstanceLoader] EventEmitterModule dependencies initialized +1ms
[Nest] 1  - 06/17/2025, 9:34:20 AM   ERROR [ExceptionHandler] Error: JWT secret file (path from AUTH_JWT_SECRET in config) does not exist at app/secrets/secret.txt
    at InstanceWrapper.useFactory [as metatype] (/app/dist/apps/api/main.js:372:35)
```

this is the docker compose:

```
services:
  attraccess:
    image: fabaccess/attraccess:nightly-latest
    container_name: attraccess
    restart: unless-stopped
    ports:
      - '80:3000'
    environment:
      # Authentication & Security
      - AUTH_JWT_ORIGIN=FILE
      - AUTH_JWT_SECRET=/app/secrets/secret.txt
      - AUTH_SESSION_SECRET=<hidden>
      - VITE_ATTRACCESS_URL=https://<hidden>.local

      # Email Configuration
      - SMTP_SERVICE=SMTP
      - SMTP_FROM=<hidden>
      - SMTP_HOST=<hidden>
      - SMTP_PORT=587
      - SMTP_USER=<hidden>
      - SMTP_PASS=<hidden>

      # Logging level
      - LOG_LEVELS=error,warn,log
    volumes:
      - ./storage:/app/storage
      - ./plugins:/app/plugins
      - ./secret:/app/secrets

```
